FMS = {}
FMS['1A'] = 'Child / Young Person Identification Form'
FMS['1B'] = 'Child / Young Person Assessment Form'
FMS['2A'] = 'Family Assessment Form'
FMS['3A'] = 'Consent Forms'
FMS['3B'] = 'Child Assent Form'
FMS['4A'] = 'Case Plan'
FMS['5A'] = 'Placement Form'
FMS['6A'] = 'Monitoring Form'
FMS['7A'] = 'Child and Caregiver Case Review Form'
FMS['8A'] = 'Young Person Case Review Form'
FMS['9A'] = 'Case closure'
FMS['10A'] = 'Transfer Form'
FMS['11A'] = 'Case Notes Form'
FMS['12A'] = 'Referral Form'
FMS['13A'] = 'FGD Form'
FMS['14A'] = 'Disability and Functioning Assessment'
FMS['15A'] = 'Caregiver Feedback Form'
FMS['16A'] = 'Child and Young Person Feedback Form'


CTS = {}
CTS['CA'] = 'Adoption'
CTS['FC'] = 'Foster Care'
CTS['IL'] = 'Supported Independent Living'
CTS['SH'] = 'Supported Child Headed HouseHold'
CTS['IC'] = 'Residential Care'
CTS['KS'] = 'Kinship Care'
CTS['CG'] = 'Guardianship'
CTS['CK'] = 'Kafaalah'
CTS['PS'] = 'Places of Safety & Temporal Shelter'

