# Generated by Django 4.1.7 on 2023-04-23 08:22

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CTIPEvents',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('event_count', models.IntegerField(default=1)),
                ('event_date', models.DateField()),
                ('form_id', models.CharField(blank=True, max_length=1)),
                ('interviewer', models.CharField(blank=True, max_length=100)),
                ('timestamp_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_void', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Trafficking Event',
                'verbose_name_plural': 'Trafficking Events',
                'db_table': 'ovc_ctip_event',
            },
        ),
        migrations.CreateModel(
            name='CTIPForms',
            fields=[
                ('form_id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('question_id', models.CharField(max_length=12)),
                ('item_value', models.CharField(max_length=5)),
                ('item_detail', models.TextField(blank=True, null=True)),
                ('timestamp_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_void', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Trafficking Form data',
                'verbose_name_plural': 'Trafficking Forms data',
                'db_table': 'ovc_ctip_form',
            },
        ),
        migrations.CreateModel(
            name='CTIPMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(blank=True, max_length=12)),
                ('case_date', models.DateField()),
                ('country', models.CharField(blank=True, max_length=2)),
                ('case_status', models.BooleanField(default=None, null=True)),
                ('case_stage', models.IntegerField(default=0)),
                ('has_consent', models.BooleanField(default=False)),
                ('consent_date', models.DateField(blank=True, null=True)),
                ('timestamp_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestamp_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_void', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Trafficked Person',
                'verbose_name_plural': 'Trafficked Persons',
                'db_table': 'ovc_ctip_main',
            },
        ),
    ]
