# Generated by Django 4.1.7 on 2023-10-30 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cpovc_forms', '0001_initial'),
        ('cpovc_ctip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctipmain',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_forms.ovccaserecord'),
        ),
    ]
