# Generated by Django 4.1.4 on 2024-06-18 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cpovc_ctip', '0002_initial'),
        ('cpovc_forms', '0001_initial'),
        ('cpovc_registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctipmain',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_registry.regperson'),
        ),
        migrations.AddField(
            model_name='ctipforms',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_ctip.ctipevents'),
        ),
        migrations.AddField(
            model_name='ctipevents',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_forms.ovccaserecord'),
        ),
        migrations.AddField(
            model_name='ctipevents',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_registry.regperson'),
        ),
    ]
