# Generated by Django 4.0 on 2023-06-23 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cpovc_ctip', '0002_initial'),
        ('cpovc_registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctipevents',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_registry.regperson'),
        ),
    ]
