# Generated by Django 4.2.16 on 2024-10-10 08:19

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AFCEvents',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('event_count', models.IntegerField(default=1)),
                ('event_date', models.DateField()),
                ('form_id', models.CharField(blank=True, max_length=3)),
                ('timestamp_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestamp_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_void', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'AFC Event',
                'verbose_name_plural': 'AFC Events',
                'db_table': 'ovc_afc_event',
            },
        ),
        migrations.CreateModel(
            name='AFCForms',
            fields=[
                ('form_id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('question_id', models.CharField(max_length=12)),
                ('item_value', models.CharField(max_length=10)),
                ('item_detail', models.TextField(blank=True, null=True)),
                ('timestamp_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestamp_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_void', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'AFC Form data',
                'verbose_name_plural': 'AFC Forms data',
                'db_table': 'ovc_afc_form',
            },
        ),
        migrations.CreateModel(
            name='AFCInfo',
            fields=[
                ('info_id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('item_id', models.CharField(max_length=12)),
                ('item_value', models.CharField(max_length=5)),
                ('item_detail', models.TextField(blank=True, null=True)),
                ('timestamp_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestamp_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_void', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'AFC Form Info',
                'verbose_name_plural': 'AFC Forms Infos',
                'db_table': 'ovc_afc_info',
            },
        ),
        migrations.CreateModel(
            name='AFCMain',
            fields=[
                ('care_id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('case_number', models.CharField(blank=True, max_length=12)),
                ('care_type', models.CharField(blank=True, max_length=5, null=True)),
                ('care_sub_type', models.CharField(blank=True, max_length=5, null=True)),
                ('school_level', models.CharField(max_length=4, null=True)),
                ('immunization_status', models.CharField(max_length=4, null=True)),
                ('case_status', models.BooleanField(default=None, null=True)),
                ('case_stage', models.IntegerField(default=0)),
                ('case_date', models.DateField()),
                ('timestamp_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestamp_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_void', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Alternative Care',
                'verbose_name_plural': 'Alternative Cares',
                'db_table': 'ovc_afc_main',
            },
        ),
        migrations.CreateModel(
            name='AFCQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(blank=True, null=True)),
                ('question_code', models.CharField(max_length=50)),
                ('form_id', models.CharField(blank=True, max_length=4, null=True)),
                ('answer_type_id', models.CharField(blank=True, max_length=4, null=True)),
                ('answer_set_id', models.IntegerField(db_index=True, null=True)),
                ('the_order', models.IntegerField(db_index=True, null=True)),
                ('timestamp_created', models.DateTimeField(auto_now=True, null=True)),
                ('timestamp_updated', models.DateTimeField(auto_now=True, null=True)),
                ('is_void', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'AFC Question',
                'verbose_name_plural': 'AFC Questions',
                'db_table': 'ovc_afc_questions',
            },
        ),
    ]
