# Generated by Django 4.1.7 on 2023-10-30 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cpovc_registry', '0001_initial'),
        ('cpovc_forms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cpovc_afc', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='afcmain',
            name='org_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_registry.regorgunit'),
        ),
        migrations.AddField(
            model_name='afcmain',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_registry.regperson'),
        ),
        migrations.AddField(
            model_name='afcinfo',
            name='care',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_afc.afcmain'),
        ),
        migrations.AddField(
            model_name='afcinfo',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_registry.regperson'),
        ),
        migrations.AddField(
            model_name='afcforms',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_afc.afcevents'),
        ),
        migrations.AddField(
            model_name='afcevents',
            name='care',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_afc.afcmain'),
        ),
        migrations.AddField(
            model_name='afcevents',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_forms.ovccaserecord'),
        ),
        migrations.AddField(
            model_name='afcevents',
            name='created_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='afcevents',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_registry.regperson'),
        ),
    ]
