# Generated by Django 4.0 on 2023-06-26 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_afc', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AFCQuestions2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(blank=True, null=True)),
                ('question_code', models.CharField(max_length=50)),
                ('form_id', models.CharField(blank=True, max_length=4, null=True)),
                ('answer_type_id', models.CharField(blank=True, max_length=4, null=True)),
                ('answer_set_id', models.IntegerField(db_index=True, null=True)),
                ('the_order', models.IntegerField(db_index=True, null=True)),
                ('timestamp_created', models.DateTimeField(auto_now=True, null=True)),
                ('timestamp_updated', models.DateTimeField(auto_now=True, null=True)),
                ('is_void', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'AFC Question2',
                'verbose_name_plural': 'AFC Questions2',
                'db_table': 'ovc_afc_questions2',
            },
        ),
    ]
