# Generated by Django 4.0 on 2023-06-26 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_afc', '0004_afcquestions2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AFCQuestions2',
        ),
    ]
