# Generated by Django 4.0.4 on 2023-04-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_afc', '0005_afcmain_care_sub_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afcinfo',
            name='item_value',
            field=models.CharField(max_length=10),
        ),
    ]
