# Generated by Django 4.1.7 on 2023-08-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_main', '0003_alter_setuplist_item_description_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='date_ended',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forms',
            name='form_area_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forms',
            name='form_guid',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='forms',
            name='form_subject_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forms',
            name='form_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='forms',
            name='form_type_id',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='forms',
            name='org_unit_id_filled_paper',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forms',
            name='person_id_filled_paper',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forms',
            name='timestamp_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
