# Generated by Django 4.1.7 on 2023-08-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_main', '0005_alter_forms_options_alter_listquestions_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listquestions',
            name='answer_field_id',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
