# Generated by Django 4.1.7 on 2023-08-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_main', '0006_listquestions_answer_field_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='listquestions',
            name='question_required',
            field=models.BooleanField(default=True),
        ),
    ]
