# Generated by Django 4.0.4 on 2022-11-20 10:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cpovc_forms', '0001_initial'),
        ('cpovc_registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCIPopulation',
            fields=[
            ],
            options={
                'verbose_name': 'CCI Population',
                'verbose_name_plural': 'CCI Populations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cpovc_forms.ovcplacement',),
        ),
        migrations.CreateModel(
            name='SIPopulation',
            fields=[
            ],
            options={
                'verbose_name': 'SI Population',
                'verbose_name_plural': 'SI Populations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cpovc_forms.ovcplacement',),
        ),
        migrations.CreateModel(
            name='SystemUsage',
            fields=[
            ],
            options={
                'verbose_name': 'System Usage',
                'verbose_name_plural': 'System Usages',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cpovc_registry.regpersonstypes',),
        ),
        migrations.CreateModel(
            name='RPTIPopulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_serial', models.CharField(max_length=40)),
                ('admission_number', models.CharField(max_length=40)),
                ('org_unit_name', models.CharField(max_length=250, null=True)),
                ('org_unit_type_id', models.CharField(max_length=4, null=True)),
                ('org_unit_type', models.CharField(max_length=250, null=True)),
                ('sex_id', models.CharField(max_length=4)),
                ('sex', models.CharField(max_length=10)),
                ('dob', models.DateField(default=django.utils.timezone.now, null=True)),
                ('age', models.IntegerField(default=0, null=True)),
                ('age_now', models.IntegerField(default=0, null=True)),
                ('age_range', models.CharField(blank=True, max_length=20, null=True)),
                ('knbs_age_range', models.CharField(blank=True, max_length=20, null=True)),
                ('admission_date', models.DateField(default=django.utils.timezone.now)),
                ('admission_type_id', models.CharField(max_length=4)),
                ('admission_type', models.CharField(max_length=250)),
                ('admission_reason_id', models.CharField(max_length=4)),
                ('admission_reason', models.CharField(max_length=250)),
                ('case_status_id', models.IntegerField(default=1)),
                ('case_status', models.CharField(max_length=20)),
                ('case_category_id', models.CharField(max_length=4)),
                ('case_category', models.CharField(max_length=250)),
                ('sub_category_id', models.CharField(max_length=4)),
                ('sub_category', models.CharField(max_length=250)),
                ('discharge_date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('discharge_type_id', models.CharField(max_length=4, null=True)),
                ('discharge_type', models.CharField(max_length=250, null=True)),
                ('county_id', models.IntegerField(default=0)),
                ('county', models.CharField(max_length=250, null=True)),
                ('sub_county_id', models.IntegerField(default=0)),
                ('sub_county', models.CharField(max_length=250, null=True)),
                ('system_date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('system_timestamp', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('is_void', models.BooleanField(default=False)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_forms.ovccaserecord')),
                ('org_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_registry.regorgunit')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_registry.regperson')),
            ],
            options={
                'verbose_name': 'Population Report',
                'verbose_name_plural': 'Population Reports',
                'db_table': 'rpt_inst_population',
            },
        ),
        migrations.CreateModel(
            name='RPTCaseLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_serial', models.CharField(max_length=40)),
                ('case_reporter_id', models.CharField(max_length=4)),
                ('case_reporter', models.CharField(max_length=250)),
                ('case_perpetrator_id', models.CharField(max_length=4, null=True)),
                ('case_perpetrator', models.CharField(max_length=250, null=True)),
                ('case_category_id', models.CharField(max_length=4)),
                ('case_category', models.CharField(max_length=250)),
                ('date_of_event', models.DateField(default=django.utils.timezone.now)),
                ('place_of_event_id', models.CharField(max_length=4)),
                ('place_of_event', models.CharField(max_length=250)),
                ('sex_id', models.CharField(max_length=4)),
                ('sex', models.CharField(max_length=10)),
                ('dob', models.DateField(default=django.utils.timezone.now, null=True)),
                ('county_id', models.IntegerField(default=0)),
                ('county', models.CharField(max_length=250, null=True)),
                ('sub_county_id', models.IntegerField(default=0)),
                ('sub_county', models.CharField(max_length=250, null=True)),
                ('org_unit_name', models.CharField(max_length=250, null=True)),
                ('case_status', models.IntegerField()),
                ('intervention_id', models.CharField(max_length=4, null=True)),
                ('intervention', models.CharField(max_length=250, null=True)),
                ('case_year', models.IntegerField(default=0)),
                ('case_month', models.IntegerField(default=0)),
                ('case_quota', models.IntegerField(default=0)),
                ('case_count', models.IntegerField(default=1)),
                ('age_range', models.CharField(blank=True, max_length=20, null=True)),
                ('knbs_age_range', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.IntegerField(default=0, null=True)),
                ('case_date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('system_date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('is_void', models.BooleanField(default=False)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_forms.ovccaserecord')),
                ('org_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_registry.regorgunit')),
            ],
            options={
                'verbose_name': 'Protection Case data',
                'verbose_name_plural': 'Protection Cases data',
                'db_table': 'rpt_case_load',
            },
        ),
        migrations.CreateModel(
            name='COPIPs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cop', models.CharField(choices=[('21', 'COP21'), ('22', 'COP22')], max_length=2)),
                ('cop_target', models.IntegerField(default=0)),
                ('funding', models.CharField(choices=[('USAID', 'USAID'), ('CDC', 'CDC'), ('DOD', 'DoD')], max_length=5)),
                ('timestamp_created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('timestamp_modified', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('is_void', models.BooleanField(default=False)),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_registry.regorgunit')),
            ],
            options={
                'verbose_name': 'COP IP Dashboard Reporting',
                'verbose_name_plural': 'COP IP Dashboard Reportings',
                'db_table': 'rpt_cop_ip',
            },
        ),
    ]
