# Generated by Django 4.1.7 on 2023-10-30 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cpovc_forms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cpovc_registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SIEvents',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('event_count', models.IntegerField(default=1)),
                ('event_date', models.DateField()),
                ('form_id', models.CharField(blank=True, max_length=10)),
                ('timestamp_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestamp_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_void', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'SI Event',
                'verbose_name_plural': 'SI Events',
                'db_table': 'ovc_si_event',
            },
        ),
        migrations.CreateModel(
            name='SIMain',
            fields=[
                ('si_id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('org_type', models.CharField(blank=True, max_length=5, null=True)),
                ('case_status', models.BooleanField(default=None, null=True)),
                ('case_stage', models.IntegerField(default=0)),
                ('case_date', models.DateField()),
                ('case_number', models.CharField(blank=True, max_length=12)),
                ('timestamp_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestamp_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_void', models.BooleanField(default=False)),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cpovc_forms.ovccaserecord')),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('org_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cpovc_registry.regorgunit')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_registry.regperson')),
                ('placement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cpovc_forms.ovcplacement')),
            ],
            options={
                'verbose_name': 'Statutory Institutions Care',
                'verbose_name_plural': 'Statutory Institutions Cares',
                'db_table': 'ovc_si_registration',
            },
        ),
        migrations.CreateModel(
            name='SIFormsAudit',
            fields=[
                ('audit_id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('form_id', models.CharField(max_length=20)),
                ('trans_type', models.CharField(max_length=10)),
                ('trans_metadata', models.TextField()),
                ('trans_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_void', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_stat_inst.sievents')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_registry.regperson')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SI Form Audit',
                'verbose_name_plural': 'SI Forms Audit',
                'db_table': 'ovc_si_audit',
            },
        ),
        migrations.CreateModel(
            name='SIForms',
            fields=[
                ('form_id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('question_id', models.CharField(max_length=50)),
                ('item_value', models.CharField(max_length=10)),
                ('item_detail', models.TextField(blank=True, null=True)),
                ('timestamp_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestamp_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_void', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_stat_inst.sievents')),
            ],
            options={
                'verbose_name': 'SI Form data',
                'verbose_name_plural': 'SI Forms data',
                'db_table': 'ovc_si_form',
            },
        ),
        migrations.AddField(
            model_name='sievents',
            name='care',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_stat_inst.simain'),
        ),
        migrations.AddField(
            model_name='sievents',
            name='created_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sievents',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_registry.regperson'),
        ),
        migrations.AddField(
            model_name='sievents',
            name='related_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cpovc_stat_inst.sievents'),
        ),
        migrations.CreateModel(
            name='SI_VacancyApp',
            fields=[
                ('vacancy', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('ref_no', models.CharField(max_length=100)),
                ('date_of_application', models.DateField(blank=True, null=True)),
                ('crc_no', models.CharField(blank=True, max_length=100, null=True)),
                ('pnc_no', models.CharField(max_length=100)),
                ('court_number', models.CharField(max_length=100)),
                ('judge_name', models.CharField(max_length=100)),
                ('child_held_at', models.CharField(max_length=100)),
                ('date_of_next_mention', models.DateField()),
                ('requesting_officer', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('sub_county_children_officer', models.CharField(max_length=100)),
                ('application_status', models.BooleanField(default=False)),
                ('date_of_approved', models.DateField(blank=True, null=True)),
                ('months_approved', models.IntegerField(default=0, null=True)),
                ('magistrate_court', models.CharField(blank=True, max_length=100, null=True)),
                ('holding_place', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_void', models.BooleanField(default=False)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approver', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cpovc_forms.ovccaserecord')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cpovc_stat_inst.sievents')),
                ('institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cpovc_registry.regorgunit')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_registry.regperson')),
            ],
            options={
                'verbose_name': 'SI Vacancy Application',
                'verbose_name_plural': 'SI Vacancy Applications',
                'db_table': 'si_vacancy',
            },
        ),
        migrations.CreateModel(
            name='SI_Document',
            fields=[
                ('doc_id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('form_id', models.CharField(max_length=10, null=True)),
                ('document_type', models.CharField(max_length=10)),
                ('document', models.FileField(upload_to='si_docs/')),
                ('is_void', models.BooleanField(default=False)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_registry.regperson')),
            ],
            options={
                'verbose_name': 'SI Document',
                'verbose_name_plural': 'SI Documents',
                'db_table': 'si_document',
            },
        ),
    ]
