# Generated by Django 4.0 on 2023-06-26 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_stat_inst', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='si_needriskassessment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='si_needriskassessment',
            name='person',
        ),
        migrations.RemoveField(
            model_name='si_needriskscale',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='si_needriskscale',
            name='person',
        ),
        migrations.RemoveField(
            model_name='si_socialinquiry',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='si_socialinquiry',
            name='person',
        ),
        migrations.RemoveField(
            model_name='si_vacancyapp',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='si_vacancyapp',
            name='person',
        ),
        migrations.DeleteModel(
            name='SI_Admission',
        ),
        migrations.DeleteModel(
            name='SI_NeedRiskAssessment',
        ),
        migrations.DeleteModel(
            name='SI_NeedRiskScale',
        ),
        migrations.DeleteModel(
            name='SI_SocialInquiry',
        ),
        migrations.DeleteModel(
            name='SI_VacancyApp',
        ),
    ]
