# Generated by Django 4.1.7 on 2023-08-14 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_stat_inst', '0002_alter_si_admission_table_simain'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='si_admission',
            table='ovc_si_main',
        ),
        migrations.DeleteModel(
            name='SIMain',
        ),
    ]
