# Generated by Django 4.0 on 2023-06-26 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_stat_inst', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='si_admission',
            table='si_main',
        ),
    ]
