# Generated by Django 4.0.4 on 2023-07-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_stat_inst', '0004_alter_si_admission_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='si_admission',
            name='institution_name',
            field=models.CharField(default='Wamumu', max_length=100),
            preserve_default=False,
        ),
    ]
