# Generated by Django 4.0.4 on 2023-07-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_stat_inst', '0005_si_admission_institution_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='si_admission',
            name='institution_type',
            field=models.CharField(choices=[('', 'Select'), ('TNRH', 'Remand Homes'), ('TNRS', 'Rehabilitation Centres'), ('TNRR', 'Rescue Centres')], max_length=5),
        ),
    ]
