# Generated by Django 4.1.7 on 2023-08-14 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cpovc_forms', '0002_initial'),
        ('cpovc_registry', '0004_photo_has_consent'),
        ('cpovc_stat_inst', '0005_simain'),
    ]

    operations = [
        migrations.CreateModel(
            name='SIEvents',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('event_count', models.IntegerField(default=1)),
                ('event_date', models.DateField()),
                ('form_id', models.CharField(blank=True, max_length=3)),
                ('timestamp_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestamp_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_void', models.BooleanField(default=False)),
                ('care', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_stat_inst.simain')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_forms.ovccaserecord')),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_registry.regperson')),
            ],
            options={
                'verbose_name': 'SI Event',
                'verbose_name_plural': 'SI Events',
                'db_table': 'ovc_si_event',
            },
        ),
        migrations.CreateModel(
            name='AFCForms',
            fields=[
                ('form_id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('question_id', models.CharField(max_length=12)),
                ('item_value', models.CharField(max_length=10)),
                ('item_detail', models.TextField(blank=True, null=True)),
                ('timestamp_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestamp_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_void', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_stat_inst.sievents')),
            ],
            options={
                'verbose_name': 'SI Form data',
                'verbose_name_plural': 'SI Forms data',
                'db_table': 'ovc_si_form',
            },
        ),
    ]
