# Generated by Django 4.0.4 on 2023-07-05 03:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_stat_inst', '0006_alter_si_admission_institution_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='si_admission',
            name='commital_court_order',
            field=models.CharField(blank=True, choices=[('ANNO', 'No'), ('AYES', 'Yes')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='si_admission',
            name='consent_form_signed',
            field=models.CharField(blank=True, choices=[('ANNO', 'No'), ('AYES', 'Yes')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='si_admission',
            name='institution_type',
            field=models.CharField(choices=[('', 'Select'), ('TNGP', 'Remand Homes'), ('TNGN', 'Rehabilitation Centres'), ('TNSA', 'Rescue Centres')], max_length=5),
        ),
        migrations.AlterField(
            model_name='si_admission',
            name='not_contact_child',
            field=models.CharField(blank=True, choices=[('ANNO', 'No'), ('AYES', 'Yes')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='si_vacancyapp',
            name='date_of_approved',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='si_vacancyapp',
            name='vacancy',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
