# Generated by Django 4.1.7 on 2023-08-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_stat_inst', '0006_sievents_afcforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='simain',
            name='org_type',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
