# Generated by Django 4.1.7 on 2023-08-15 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_stat_inst', '0007_simain_org_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='si_vacancyapp',
            options={'verbose_name': 'SI Vacancy Application', 'verbose_name_plural': 'SI Vacancy Applications'},
        ),
    ]
