# Generated by Django 4.0.4 on 2023-07-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_stat_inst', '0007_alter_si_admission_commital_court_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='si_vacancyapp',
            name='application_status',
            field=models.CharField(choices=[('W', 'Waiting'), ('A', 'Approved'), ('D', 'Denied')], default='W', max_length=4),
        ),
    ]
