# Generated by Django 4.0.4 on 2023-07-05 09:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_stat_inst', '0008_alter_si_vacancyapp_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='si_vacancyapp',
            name='updated_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
