# Generated by Django 4.1.7 on 2023-08-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_stat_inst', '0008_alter_si_vacancyapp_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='si_admission',
            name='commital_court_order',
            field=models.CharField(blank=True, choices=[('AYES', 'Yes'), ('ANNO', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='si_admission',
            name='consent_form_signed',
            field=models.CharField(blank=True, choices=[('AYES', 'Yes'), ('ANNO', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='si_admission',
            name='not_contact_child',
            field=models.CharField(blank=True, choices=[('AYES', 'Yes'), ('ANNO', 'No')], max_length=5, null=True),
        ),
    ]
