# Generated by Django 4.0.4 on 2023-07-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_stat_inst', '0009_si_vacancyapp_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='si_vacancyapp',
            name='cci_placed',
            field=models.CharField(max_length=20),
        ),
    ]
