# Generated by Django 4.1.7 on 2023-08-15 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cpovc_registry', '0004_photo_has_consent'),
        ('cpovc_stat_inst', '0009_alter_si_admission_commital_court_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='si_vacancyapp',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='si_vacancyapp',
            name='institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cpovc_registry.regorgunit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='si_vacancyapp',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='si_vacancyapp',
            name='date_of_approved',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='si_vacancyapp',
            name='magistrate_court',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='si_vacancyapp',
            name='months_approved',
            field=models.IntegerField(default=0),
        ),
    ]
