# Generated by Django 4.1.7 on 2023-08-15 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_registry', '0004_photo_has_consent'),
        ('cpovc_stat_inst', '0010_si_vacancyapp_approved_by_si_vacancyapp_institution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='si_vacancyapp',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cpovc_registry.regorgunit'),
        ),
        migrations.AlterField(
            model_name='si_vacancyapp',
            name='months_approved',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
