# Generated by Django 4.1.7 on 2023-08-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_stat_inst', '0011_alter_si_vacancyapp_institution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='si_vacancyapp',
            name='cci_placed',
        ),
        migrations.AddField(
            model_name='si_vacancyapp',
            name='holding_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
