# Generated by Django 4.1.7 on 2023-08-16 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_forms', '0002_initial'),
        ('cpovc_stat_inst', '0012_remove_si_vacancyapp_cci_placed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sievents',
            name='case',
        ),
        migrations.AlterField(
            model_name='simain',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cpovc_forms.ovccaserecord'),
        ),
    ]
