# Generated by Django 4.1.7 on 2023-08-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_stat_inst', '0013_remove_sievents_case_alter_simain_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='simain',
            name='case_number',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
