# Generated by Django 4.1.7 on 2023-08-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_stat_inst', '0014_simain_case_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sievents',
            name='form_id',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
