# Generated by Django 4.0.4 on 2023-07-14 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_stat_inst', '0014_si_referral_delete_referral'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SI_Referral',
        ),
    ]
