# Generated by Django 4.0.4 on 2023-07-16 05:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_stat_inst', '0016_si_referral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='si_referral',
            name='id',
        ),
        migrations.AddField(
            model_name='si_admission',
            name='admission_number',
            field=models.CharField(default='06d77f39-461f-446e-881d-992b258de401', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='si_referral',
            name='referral',
            field=models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False),
        ),
    ]
