# Generated by Django 4.1.7 on 2023-08-16 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_stat_inst', '0016_alter_sievents_form_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AFCForms',
            new_name='SIForms',
        ),
    ]
