# Generated by Django 4.0.4 on 2023-07-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_stat_inst', '0017_remove_si_referral_id_si_admission_admission_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='si_referral',
            name='referral',
        ),
        migrations.AddField(
            model_name='si_referral',
            name='id',
            field=models.AutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='si_referral',
            name='updated_at',
            field=models.DateTimeField(default=2),
            preserve_default=False,
        ),
    ]
