# Generated by Django 4.1.7 on 2023-08-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_stat_inst', '0017_rename_afcforms_siforms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siforms',
            name='question_id',
            field=models.CharField(max_length=50),
        ),
    ]
