# Generated by Django 4.0.4 on 2023-07-16 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_stat_inst', '0018_remove_si_referral_referral_si_referral_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SI_Referral',
        ),
    ]
