# Generated by Django 4.0.4 on 2023-07-16 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_registry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cpovc_stat_inst', '0020_si_referral'),
    ]

    operations = [
        migrations.CreateModel(
            name='SI_Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(max_length=50)),
                ('date_released', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('id_no', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('occupation', models.CharField(max_length=100)),
                ('residence', models.CharField(max_length=200)),
                ('relation_to_child', models.CharField(max_length=100)),
                ('is_void', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_registry.regperson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'si_releases',
            },
        ),
    ]
