# Generated by Django 4.0.4 on 2023-07-16 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_stat_inst', '0021_si_release'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='si_admission',
            name='admission_number',
        ),
    ]
