# Generated by Django 4.0.4 on 2023-07-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_stat_inst', '0022_remove_si_admission_admission_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='si_admission',
            name='admission_number',
            field=models.CharField(default=676767, max_length=100),
            preserve_default=False,
        ),
    ]
