# Generated by Django 4.0.4 on 2023-07-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_stat_inst', '0023_si_admission_admission_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='si_admission',
            name='institution_type',
            field=models.CharField(choices=[('default_option', 'Select'), ('TNGP', 'Remand Homes'), ('TNGN', 'Rehabilitation Centres'), ('TNSA', 'Rescue Centres')], max_length=15),
        ),
    ]
