# Generated by Django 4.0.4 on 2023-07-16 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cpovc_stat_inst', '0024_alter_si_admission_institution_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='si_admission',
            name='is_place',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='si_admission',
            name='is_placed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='si_admission',
            name='place_approved_at',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='si_admission',
            name='place_approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='si_admission',
            name='place_created_at',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='si_admission',
            name='placed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='si_admission',
            name='placement_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='si_admission',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
