# Generated by Django 4.0.4 on 2023-07-16 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cpovc_stat_inst', '0025_si_admission_is_place_si_admission_is_placed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='si_admission',
            old_name='is_place',
            new_name='is_placement_approved',
        ),
        migrations.RemoveField(
            model_name='si_admission',
            name='placement_approved',
        ),
        migrations.AlterField(
            model_name='si_admission',
            name='placed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
