# Generated by Django 4.0.4 on 2023-07-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_stat_inst', '0026_rename_is_place_si_admission_is_placement_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='si_admission',
            name='place_approved_at',
            field=models.DateField(null=True),
        ),
    ]
