# Generated by Django 4.1.7 on 2023-05-02 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_registry', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
