# Generated by Django 4.1.7 on 2023-06-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_registry', '0003_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='has_consent',
            field=models.BooleanField(default=False),
        ),
    ]
