# Generated by Django 4.0.2 on 2022-08-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_forms', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ovccaserecord',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ovccaserecord',
            name='gender',
            field=models.CharField(default='Female', max_length=10),
        ),
    ]
