# Generated by Django 4.0.2 on 2022-08-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_forms', '0003_alter_ovccaserecord_age_alter_ovccaserecord_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ovccasecategory',
            name='case_category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ovccasecategory',
            name='case_nature',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ovccasecategory',
            name='place_of_event',
            field=models.CharField(max_length=20),
        ),
    ]
