# Generated by Django 4.0.2 on 2022-08-13 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_forms', '0004_alter_ovccasecategory_case_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ovccasecategory',
            name='date_of_event',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
