# Generated by Django 4.0.4 on 2023-04-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_auth', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='password_changed_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
