# Report names
RPTS = {}
RPTS[1] = 'DATIM'
RPTS[2] = 'PEPFAR'
RPTS[3] = 'KPI'
RPTS[4] = 'DATIM'
RPTS[5] = 'DATIM'
RPTS[6] = 'OTHER'
# ------------------ GoK------------
RPTS[100] = 'CaseLoad'
RPTS[105] = 'MissingChildren'
RPTS[106] = 'VAC'
#
ORPTS = {}
ORPTS[1] = 'Registration list'
ORPTS[2] = 'Registration by HH'
ORPTS[3] = 'CSI'
ORPTS[4] = 'CHV monthly RR'
ORPTS[5] = 'List of OVC not served'
ORPTS[6] = 'PEPFAR detailed summary'
ORPTS[7] = 'Registration by CHV'
ORPTS[8] = 'Beneficiary list'
ORPTS[9] = 'Form1A summary'
ORPTS[10] = 'Needs vs Served by domain'
ORPTS[11] = 'Form1B summary'
ORPTS[12] = 'List of Served'
# GoK Reports
GRPTS = {}
GRPTS[0] = 'CaseLoad'
GRPTS[1] = 'KNBS'
GRPTS[2] = 'CaseLoad'
GRPTS[3] = 'Institution Population Returns'
GRPTS[4] = 'Health'
GRPTS[5] = 'Ad Hoc'
# Adhoc
ADHC = {}
ADHC[1] = 'Organisation Unit'
ADHC[2] = 'Institution Register'
ADHC[3] = 'Case Load Summary'
ADHC[4] = 'Excel Tool A'
ADHC[5] = 'Missing Children'
ADHC[6] = 'Violence Against Children (VAC)'
ADHC[7] = 'Children in Emergencies'
# AFC Reports
ACRPTS = {}
ACRPTS[1] = 'AFC Summary'
ACRPTS[2] = 'Identification'
ACRPTS[3] = 'Assessment - Child'
ACRPTS[4] = 'Assessment - Family'
ACRPTS[5] = 'Case Plan'
ACRPTS[6] = 'Placement'
ACRPTS[7] = 'Monitoring'
ACRPTS[8] = 'Case Review - Child and Caregiver'
ACRPTS[9] = 'Case Review - Young Adult'
ACRPTS[10] = 'Closure'
ACRPTS[11] = 'Consent'
ACRPTS[12] = 'Transfer'
ACRPTS[13] = 'Referral'
ACRPTS[14] = 'Disability'
ACRPTS[15] = 'Feedback - Caregiver'
ACRPTS[16] = 'Feedback - Young Adult'
